@startuml

package com.testingo {
    package controllers
    package datastructures
    package dataflow
    package controllers.support
}
package com.yelp
package com.google.gson
package de.greenrobot.event
package com.loopj.android.http


controllers --> controllers.support
controllers --> dataflow
controllers --> datastructures
controllers --> com.yelp
controllers --> de.greenrobot.event
dataflow --> de.greenrobot.event
dataflow --> com.loopj.android.http
datastructures --> com.google.gson

@enduml